### PR TITLE
Treasure map location updates for Stormhaven

### PR DESCRIPTION
**Pull request by tiker**
Update pin locations to be more accurate in Stormhaven.

### CODE REVIEW

**Comment by Scootworks** [comment]
@tiker thanks a lot for your inputs. Could you test the recent 'dev branch' if everything works fine?

**Comment by tiker** [comment]
Downloading it now.  (I still have more updates to post.)

**Comment by Scootworks** [comment]
> Downloading it now. (I still have more updates to post.)

cool thx. you could add changed stuff directly to the dev branch. I‘m just curious, the positions you have adjusted have only small changes. What exactly is different from your now positions to the old ones?

**Comment by tiker** [comment]
No issues with the development version so far.  I'll try making updates to the dev branch and will let you know if there are any issues.

Some markers are way off, some are slightly off.  Since I'm updating markers that were way off, I might as well update all of them to move the X on the treasure map dirt mound and not somewhere close to it.

**Pull request closed without merging**
